### ISSUE TITLE
Cannot find package

### ISSUE THREAD

**Issue by xiqning** [amsokol/openshift-golang-template#1]
package github.com/amsokol/openshift-golang-template/example/pkg/cmd/server: cannot find package "github.com/amsokol/openshift-golang-template/example/pkg/cmd/server" in any of: /usr/local/go/src/github.com/amsokol/openshift-golang-template/example/pkg/cmd/server (from $GOROOT)
	/opt/app-root/src/github.com/amsokol/openshift-golang-template/example/pkg/cmd/server (from $GOPATH)
package github.com/amsokol/openshift-golang-template/example/pkg/fake: cannot find package "github.com/amsokol/openshift-golang-template/example/pkg/fake" in any of:
	/usr/local/go/src/github.com/amsokol/openshift-golang-template/example/pkg/fake (from $GOROOT)
	/opt/app-root/src/github.com/amsokol/openshift-golang-template/example/pkg/fake (from $GOPATH)
github.com/pressly/chi (download)
package github.com/amsokol/openshift-golang-template/example-golang-dep/pkg/cmd/cli: cannot find package "github.com/amsokol/openshift-golang-template/example-golang-dep/pkg/cmd/cli" in any of:
	/usr/local/go/src/github.com/amsokol/openshift-golang-template/example-golang-dep/pkg/cmd/cli (from $GOROOT)
	/opt/app-root/src/github.com/amsokol/openshift-golang-template/example-golang-dep/pkg/cmd/cli (from $GOPATH)
package github.com/amsokol/openshift-golang-template/example-golang-dep/pkg/cmd/server: cannot find package "github.com/amsokol/openshift-golang-template/example-golang-dep/pkg/cmd/server" in any of:
	/usr/local/go/src/github.com/amsokol/openshift-golang-template/example-golang-dep/pkg/cmd/server (from $GOROOT)
	/opt/app-root/src/github.com/amsokol/openshift-golang-template/example-golang-dep/pkg/cmd/server (from $GOPATH)
package github.com/amsokol/openshift-golang-template/example-golang-dep/pkg/fake: cannot find package "github.com/amsokol/openshift-golang-template/example-golang-dep/pkg/fake" in any of:
	/usr/local/go/src/github.com/amsokol/openshift-golang-template/example-golang-dep/pkg/fake (from $GOROOT)
	/opt/app-root/src/github.com/amsokol/openshift-golang-template/example-golang-dep/pkg/fake (from $GOPATH)

It seem like that the file S2I/.s2i/bin/assemble have problem. We should update the connent "cp -Rf /tmp/src/.  ./" to "cp -Rf /tmp/s2i*/upload/src/.  ./"   The env CONTEXT_DIR in openshift looks like named SOURCE_CONTEXT_DIR

**Comment by amsokol** [comment]
Dear @xiqning,

Could you please ensure that you provide GOPROJECT_ROOT and GOPROJECT_CMD environment variables to builder as described [here](https://github.com/amsokol/openshift-golang-template#how-to) sections 11-13.
For example if you are going to run example project `example-golang-dep` you need to set the following:
GOPROJECT_ROOT is "github.com/amsokol/openshift-golang-template/example-golang-dep"
GOPROJECT_CMD is "cmd/server"

**Comment by xiqning** [comment]
Thanks @amsokol  Yes, i am sure that i provide both environment variables. 
To resolve the first problem , I updade the file S2I/.s2i/bin/assemble to modify the connent "cp -Rf /tmp/src/. ./" as   "cp -Rf /tmp/s2i*/upload/src/. ./" 
Then  I set the following:
    GOPROJECT_ROOT="**_github.com/amsokol/openshift-golang-template_**"
    GOPROJECT_CMD="_**example-golang-dep/cmd/server**_"
Finally the builder work well.

But if I did not provide the environment variables GOPROJECT_ROOT , 
only set  CONTEXT_DIR=/example-golang-dep , the output is:

_---> Сlarify the root package for go application
**CONTEXT_DIR is empty, so root package is ""**
---> Installing application source in folder "/opt/app-root/src/"
---> Do not use dependency manager - run 'go get'
---> Downloading dependencies...
github.com/amsokol/openshift-golang-template (download)_

then I find the follow information:
**SOURCE_CONTEXT_DIR      /example-golang-dep**

So whether the environment variable CONTEXT_DIR is updated to SOURCE_CONTEXT_DIR？

**Comment by amsokol** [comment]
Dear @xiqning,

Thanks for your email.

I changed assemble file to use `SOURCE_REPOSITORY` and `SOURCE_CONTEXT_DIR` environment variables.
Thanks!

I re-tested current version of `openshift-golang-template` on OpenShift Origin 1.5.
Everything is OK.

I also download latest S2I and create sample project from scratch as a test.
It adds `"cp -Rf /tmp/src/. ./"` to `assemble` file, not `/tmp/s2i*/upload/src/`.
May be you are using not latest version of OpenShift.
For such case I added the following to `assemble` file:
```
if test -d /tmp/src
then
	cp -Rf /tmp/src/. ./
else
	# for backwards compatibility
	cp -Rf /tmp/s2i*/upload/src/. ./
fi
```

Could you please try latest (v1.8.1-5) version and let me know result.

Thanks,
Aleksandr

**Comment by xiqning** [comment]
Dear @amsokol 

Thanks for your reply.

I am used latest (v1.8.1-5) version and everything is ok.
Thank you once again.

Xiqning
