### ISSUE TITLE
add golang 1.9 support

### ISSUE THREAD

**Issue by walnut-tom** [amsokol/openshift-golang-template#10]
golang 1.9 has released.
https://github.com/golang/go/releases/tag/go1.9

**Comment by amsokol** [comment]
Hi,

Great news!
I add 1.9 soon.

**Comment by devcodewak** [comment]
@amsokol

Look forward to go1.9 template, some procedures using the sync.map attribute, must be compiled 1.9. 
Thx.

**Comment by amsokol** [comment]
@walnut-tom , @devcodewak ,

Done.
I've commited update to Github and uploaded image 1.9.0-1 to Docker hub.
I have no OpenShift environment now so I need you have to test this one.
Please take master to test and let me now results plz.
Thanks!

**Comment by amsokol** [comment]
Done
