### ISSUE TITLE
Permission denied when run goapplication2run

### ISSUE THREAD

**Issue by guiferpa** [amsokol/openshift-golang-template#11]
Hi, I using this project as temaplate for OpenShift Origin but don't work it. The OpenShift report an error with the message: 
```sh
---> Run apllication
---> /usr/libexec/s2i/run: line 13: /opt/app-root/bin/goapplication2run: Permission denied
```

I think open an PR to fix it, what do you think?

**Comment by amsokol** [comment]
Hi @guiferpa 

I see you have closed the issue.
Why?

**Comment by guiferpa** [comment]
Hi @amsokol, thanks by your attention. I closed this issue because I was wearing the image wrong. When to compile the package I was using wrong package. hahahahah'
